<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <link href="https://cdn.bootcss.com/bulma/0.6.2/css/bulma.css" rel="stylesheet">
</head>
<body>
    <section class="section">
        <div class="container">
                <h1 class="title">Logged in as : <?= $_SESSION['user_name'] ?></h1>
                <hr>
                <form action="/logout" method="post">
                    <button class="button is-dark" type="submit">logout</button>
                </form>
        </div>
    </section>  
</body>
</html>