<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register</title>
</head>
<body>
    <form action="/register" method="post">
    Email:<input type="email" name="email">
    Name:<input type="text" name="name">
    Password:<input type="password" name="password">
    Password Confirm:<input type="password" name="password_confirmation">
    <button type="submit">Register</button>
    </form>
</body>
</html>